# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisso',
            name='datahorafim',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='compromisso',
            name='datahorainicial',
            field=models.DateField(blank=True, null=True),
        ),
    ]
